src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\ManyToMany(targetEntity=Evenement::class, inversedBy="users")
     */
    private $evenement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @Vich\UploadableField(mapping="poster_file", fileNameProperty="picture")
     * @var File | null
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/png", "image/webp", "image/jpg"},
     * )
     */
    private $posterFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $response;

    /**
     * @ORM\OneToMany(targetEntity=UserEvent::class, mappedBy="user")
     */
    private $userEvents;

    public function __construct()
    {
        $this->evenement = new ArrayCollection();
        $this->userEvents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }


    /**
     * @return Collection|Evenement[]
     */
    public function getEvenement(): Collection
    {
        return $this->evenement;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenement->contains($evenement)) {
            $this->evenement[] = $evenement;
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        $this->evenement->removeElement($evenement);

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function setPosterFile(File $image = null): User
    {
        $this->posterFile = $image;
        return $this;
    }

    public function getPosterFile(): ?File
    {
        return $this->posterFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdateAt(File $image = null)
    {
        $this->updatedAt = $image;
        if ($image) {
            $this->updatedAt = new DateTime('now');
        }
    }

    public function getResponse(): ?int
    {
        return $this->response;
    }

    public function setResponse(?int $response): self
    {
        $this->response = $response;

        return $this;
    }

    /**
     * @return Collection|UserEvent[]
     */
    public function getUserEvents(): Collection
    {
        return $this->userEvents;
    }

    public function addUserEvent(UserEvent $userEvent): self
    {
        if (!$this->userEvents->contains($userEvent)) {
            $this->userEvents[] = $userEvent;
            $userEvent->setUser($this);
        }

        return $this;
    }

    public function removeUserEvent(UserEvent $userEvent): self
    {
        if ($this->userEvents->removeElement($userEvent)) {
            // set the owning side to null (unless already changed)
            if ($userEvent->getUser() === $this) {
                $userEvent->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationFormType;
use App\Security\EmailVerifier;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Message;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{

    private EmailVerifier $emailVerifier;

    public function __construct(EmailVerifier $emailVerifier)
    {
        $this->emailVerifier = $emailVerifier;
    }

    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route('/register', name: 'app_register')]
    public function register(Request $request, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $passwordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $user->setRoles(['ROLE_CONTRIBUTOR']);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            // generate a signed url and email it to the user
            $this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
                (new TemplatedEmail())
                    ->from(new Address('dude@gmail.com', 'Dude'))
                    ->to($user->getEmail())
                    ->subject('Please Confirm your Email')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );
            // do anything else you need here, like send an email
            $this->addFlash('success', 'Veuillez valider votre adresse e-mail.');

            return $this->redirectToRoute('app_login');
        }

        return $this->render('security/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}

    <!-- This is an example component -->
    <div class="h-screen font-sans login bg-cover">
        {% for message in app.flashes('success') %}
            <div role="alert">
                <div class="bg-green-500 text-center text-white font-bold rounded-t px-4 py-2">
                    Success
                </div>
                <div class="border text-center border-t-0 border-green-400 rounded-b bg-green-100 px-4 py-3 text-green-700">
                    <p>{{ message }}</p>
                </div>
            </div>
        {% endfor %}
        <div class="container mx-auto h-full flex flex-1 justify-center items-center">
            <div class="w-full max-w-lg">
                <div class="leading-loose">
                    <form method="post" class="max-w-sm m-4 p-10 bg-white bg-opacity-25 rounded shadow-xl">
                        {% if error %}
                            <div class="alert alert-danger text-center font-black text-red-500" > ⚠️ Adresse ou mot de passe incorrect</div>
                        {% endif %}

                        {% if app.user %}
                            <div class="mb-3">
                                You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
                            </div>
                        {% endif %}

                        {% if app.user %}

                        {% else %}
                        <p class="text-white font-medium text-center text-lg font-bold">LOGIN</p>
                        <div class="">
                            <label class="block text-sm text-white" for="inputEmail">E-mail</label>
                            <input class="w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white" type="email" id="inputEmail"
                                   placeholder="e-mail" value="{{ last_username }}" name="email" aria-label="email" autocomplete="email" required>
                        </div>
                        <div class="mt-2">
                            <label class="block text-sm text-white">Mot de passe</label>
                            <input class="w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white"
                                   type="password" name="password" id="inputPassword" autocomplete="current-password" placeholder="mot de passe" arial-label="password" required>
                        </div>
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">


                        <div class="mt-4 items-center flex justify-between">
                            <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 hover:bg-gray-800 rounded"
                                    type="submit">Valider</button>
                            <a class="inline-block right-0 align-baseline font-bold text-sm text-500 text-white hover:text-red-400"
                               href="{{ path('app_forgot_password_request') }}">Mot de passe oublié ?</a>
                        </div>
                    </form>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <style>
        .login{
            /*
              background: url('https://tailwindadmin.netlify.app/dist/images/login-new.jpeg');
            */
            background: url('https://www.tremblant.ca/-/media/tremblant/things-to-do/events/beach-party/tremblant-beach-party-l.ashx');
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>

{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}


    <div class="h-screen font-sans login bg-cover">
        <div class="container mx-auto h-full flex flex-1 justify-center items-center">
            <div class="w-full max-w-lg">
                <div class="leading-loose">
                    <form method="post" class="max-w-sm m-4 p-10 bg-white bg-opacity-25 rounded shadow-xl">
                        {% for flashError in app.flashes('verify_email_error') %}
                            <div class="alert alert-danger" role="alert">{{ flashError }}</div>
                        {% endfor %}
                        {{ form_start(registrationForm) }}
                        <p class="text-white font-medium text-center text-lg font-bold">Création d'un compte</p>
                        <div class="">
                            {{ form_row(registrationForm.email, {
                                attr: {'class': "w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white"},
                                label_attr: {'class': 'mt-4 block text-sm text-white'},
                                label: "Entrez une adresse mail"
                            }) }}
                        </div>
                        <div class="mt-2">
                            {{ form_row(registrationForm.plainPassword, {
                                attr: {'class': "w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white"},
                                label_attr: {'class': 'mt-4 block text-sm text-white'},
                                label: "Entrez un mot de passe"
                            }) }}
                        </div>
                        <div class="">
                            {{ form_row(registrationForm.nom, {
                                attr: {'class': "w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white"},
                                label_attr: {'class': 'mt-4 block text-sm text-white'},
                                label: "Entrez un nom"
                            }) }}
                        </div>
                        <div class="">
                            {{ form_row(registrationForm.prenom, {
                                attr: {'class': "w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white"},
                                label_attr: {'class': 'mt-4 block text-sm text-white'},
                                label: "Entrez un Prenom"
                            }) }}
                        </div>
                        <div class="mb-2">
                            {{ form_row(registrationForm.posterFile, {
                                label_attr: {'class': 'mt-4 block text-sm text-white'},
                                label: "Choisir une photo de profil (non obligatoire)"
                            }) }}
                        </div>
                        {{ form_row(registrationForm.agreeTerms) }}

                        <div class="mt-4 items-center flex justify-between">
                            <button class=" btn px-4 py-1 text-white font-light tracking-wider bg-gray-900 hover:bg-gray-800 rounded"
                                    type="submit">Valider</button>
                            {{ form_end(registrationForm) }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <style>
        .login{
            /*
              background: url('https://tailwindadmin.netlify.app/dist/images/login-new.jpeg');
            */
            background: url('https://www.tremblant.ca/-/media/tremblant/things-to-do/events/beach-party/tremblant-beach-party-l.ashx');
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
{% endblock %}