src/Entity/Bar.php
<?php

namespace App\Entity;

use App\Repository\BarRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
//Ici on importe le package Vich, que l’on utilisera sous l’alias “Vich”
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=BarRepository::class)
 * @Vich\Uploadable
 */
class Bar
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @Vich\UploadableField(mapping="poster_file", fileNameProperty="picture")
     * @var File | null
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/png", "image/webp", "image/jpg"},
     * )
     */
    private $posterFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="integer")
     */
    private $codePostal;


    /**
     * @ORM\ManyToMany(targetEntity=Evenement::class, inversedBy="bars")
     */
    private $event;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlName;

    public function __construct()
    {
        $this->event = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->codePostal;
    }

    public function setCodePostal(int $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvent(): Collection
    {
        return $this->event;
    }

    public function addEvent(Evenement $event): self
    {
        if (!$this->event->contains($event)) {
            $this->event[] = $event;
        }

        return $this;
    }

    public function removeEvent(Evenement $event): self
    {
        $this->event->removeElement($event);

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function setPosterFile(File $image = null): Bar
    {
        $this->posterFile = $image;
        return $this;
    }

    public function getPosterFile(): ?File
    {
        return $this->posterFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdateAt(File $image = null)
    {
        $this->updatedAt = $image;
        if ($image) {
            $this->updatedAt = new DateTime('now');
        }
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUrlName(): ?string
    {
        return $this->urlName;
    }

    public function setUrlName(string $urlName): self
    {
        $this->urlName = $urlName;

        return $this;
    }
}

src/Entity/UserEvent.php
<?php

namespace App\Entity;

use App\Repository\UserEventRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserEventRepository::class)
 */
class UserEvent
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="userEvents")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Evenement::class, inversedBy="userEvents")
     */
    private $event;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Response;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEvent(): ?Evenement
    {
        return $this->event;
    }

    public function setEvent(?Evenement $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getResponse(): ?int
    {
        return $this->Response;
    }

    public function setResponse(?int $Response): self
    {
        $this->Response = $Response;

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Bar;
use App\Entity\Evenement;
use App\Entity\Hotel;
use App\Entity\Jet;
use App\Entity\Plage;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre', TextType::class)
            ->add('description', TextType::class)
            ->add('date', DateType::class)
            ->add('ville', TextType::class)
            ->add('pays')
            ->add('posterFile', VichFileType::class, [
                'required'      => false,
                'allow_delete'  => true, // not mandatory, default is true
                'download_uri' => true, // not mandatory, default is true
            ])
            ->add('bars', EntityType::class, [
                'class' => Bar::class,
                'choice_label' => function (Bar $bar){
                return $bar->getNom().' '. $bar->getVille().'-'. $bar->getPays();
                },
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
            ])
            ->add('hotels', EntityType::class, [
                'class' => Hotel::class,
                'choice_label' => function (Hotel $hotel){
                return $hotel->getNom().' '.$hotel->getVille().'-'.$hotel->getPays();
                },
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
            ])
            ->add('jets', EntityType::class, [
                'class' => Jet::class,
                'choice_label' => 'nom',
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Entity\Event;
use App\Entity\UserEvent;
use App\Entity\UserEventRole;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use App\Repository\UserEventRepository;
use App\Repository\UserEventRoleRepository;
use App\Service\UrlName;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/evenement', name: 'evenement_')]
class EvenementController extends AbstractController
{
    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    /**
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, UrlName $urlName): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $urlName = $urlName->generate($evenement->getTitre());
            $evenement->setUrlName($urlName);
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{urlName}', name: 'show', methods: ['GET'])]
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    #[Route('/{urlName}/edit', name: 'edit', methods: ['GET', 'POST'])]
    /**
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Evenement $evenement): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    /**
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Evenement $evenement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
    }


    /**
     * @Route("/{id}/participe/{participe}", name="participe", methods={"GET"})
     */
    public function participe(
        Request $request,
        Evenement $event,
        UserEventRepository $userRepository,
        int $participe
    ): Response {
        $userEventRole = $userRepository->findOneBy(['user' => $this->getUser(), 'event' => $event]);
        if (!$userEventRole) {
            $userEventRole = new UserEvent();
            $user = $this->getUser();
            $userEventRole->setUser($user);
            $userEventRole->setResponse($participe);
            $userEventRole->setEvent($event);
            $this->getDoctrine()->getManager()->persist($userEventRole);
        }
        $userEventRole->setResponse($participe);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('evenement_index');
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/evenement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}

templates/evenement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement index{% endblock %}

{% block body %}

    <div class="bg-white">
    <h4 class="text-2xl text-center mt-8 font-bold">Séction Evénements Privés</h4>
    {% if is_granted("ROLE_ADMIN") %}
    <a href="{{ path('evenement_new') }}">Create new</a>
    {% endif %}
    <div class="flex justify-end mb-4 mr-2">
        <a href="{{ path('home') }}">Retour/a>
    </div>
    {% for evenement in evenements %}
        {% if (loop.index %2) != 0 %}
        {% if is_granted("ROLE_ADMIN") %}
            <a class="ml-2" href="{{ path('evenement_edit', {'urlName': evenement.urlName}) }}">Editer</a>
            {% endif %}
            <div class="flex -mx-1 mb-5">
            <div class="w-1/2 px-1">
                <a href="{{ path('evenement_show', {'urlName': evenement.urlName}) }}" class="block mb-2 p-5 rounded overflow-hidden transform transition-all duration-300 scale-100 hover:scale-95" style="background: url({{ asset('/uploads/' ~ evenement.picture) }}) center; background-size: cover;">
                    <div class="h-48"></div>
                    <h3 class="text-lg font-bold text-blue-100 mt-12 leading-tight">{{ evenement.titre }}</h3>
                    <div class="flex">
                        <h3 class="text-lg font-bold text-blue-100 leading-tight">{{ evenement.description }} XX </h3>
                    </div>
                    <div class="flex">
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ evenement.ville }} - </h3>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ evenement.pays }}</h3>
                    </div>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ evenement.date|date('d/m/Y') }}</h3>
                </a>
            </div>
        {% else %}
            <div class="w-1/2 px-1">
            <a href="{{ path('evenement_show', {'urlName': evenement.urlName}) }}" class="block mb-2 p-5 rounded overflow-hidden transform transition-all duration-300 scale-100 hover:scale-95" style="background: url({{ asset('/uploads/' ~ evenement.picture) }}) center; background-size: cover;">
                <div class="h-48"></div>
                <h3 class="text-lg font-bold text-blue-100 mt-12 leading-tight">{{ evenement.titre }}</h3>
                <div class="flex">
                    <h3 class="text-lg font-bold text-blue-100 leading-tight">{{ evenement.description }} XX </h3>
                </div>
                <div class="flex">
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ evenement.ville }} - </h3>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ evenement.pays }}</h3>
                </div>
                <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ evenement.date|date('d/m/Y') }}</h3>
            </a>
            {% if is_granted("ROLE_ADMIN") %}
                <a class="ml-2" href="{{ path('evenement_edit', {'urlName': evenement.urlName}) }}">Editer</a>
                {% endif %}
            </div>
            </div>
            </div>
        {% endif %}
    {% else %}
        <tr>
            <td colspan="8">no records found</td>
        </tr>
        </div>
    {% endfor %}
{% endblock %}

templates/evenement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Evenement{% endblock %}

{% block body %}
    <h1>Create new Evenement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('evenement_index') }}">back to list</a>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}

    <div class="text-center mt-8 mb-8 font-extrabold">
    {{ evenement.titre }}
    </div>
    <div class="flex justify-end mb-4 mr-2">
        <a href="{{ path('evenement_index') }}">Revenir aux choix d'evènements</a>
    </div>
    {% for bar in evenement.bars %}
    <div class="mb-5">
        <a href="{{ path('bar_show', {'urlName': bar.urlName}) }}" class="block rounded-lg relative p-5 transform transition-all duration-300 scale-100 hover:scale-95" style="background: url({{ asset('/uploads/' ~ bar.picture) }}) center; background-size: cover;">
            <div class="h-48"></div>
            <h2 class="text-blue-100 text-2xl font-bold leading-tight mb-3 pr-5">{{ bar.nom }} XX {{ evenement.titre }}</h2>
            <div class="flex w-full items-center text-sm text-gray-300 font-medium">
                <div class="flex-1 flex items-center">
                </div>
            </div>
            <div class="text-blue-100">
            {{ evenement.date ? evenement.date|date('d-m-Y') : '' }}
            </div>
        </a>
    </div>


        <!-- This is an example component -->
        <div class="container mx-auto my-5">

            <div class="relative rounded-lg flex flex-col md:flex-row items-center md:shadow-xl md:h-72 mx-2">

                <div class="z-0 order-1 md:order-2 relative w-full md:w-2/5 h-80 md:h-full overflow-hidden rounded-lg md:rounded-none md:rounded-r-lg">
                    <div class="absolute inset-0 w-full h-full object-fill object-center bg-blue-400 bg-opacity-30 bg-cover bg-bottom" style="background-image: url({{ asset('/uploads/' ~ evenement.picture) }}); background-blend-mode: multiply;"></div>
                    <div class="md:hidden absolute inset-0 h-full p-6 pb-6 flex flex-col-reverse justify-start items-start bg-gradient-to-b from-transparent via-transparent to-gray-900">
                        <h3 class="w-full font-bold text-2xl text-white leading-tight mb-2"></h3>
                        <h4 class="w-full text-xl text-gray-100 leading-tight"></h4>
                    </div>
                    <svg class="hidden md:block absolute inset-y-0 h-full w-24 fill-current text-white -ml-12" viewBox="0 0 100 100" preserveAspectRatio="none">
                        <polygon points="50,0 100,0 50,100 0,100" />
                    </svg>
                </div>

                <div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 bg-white flex items-center -mt-6 md:mt-0">
                    <div class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none">
                        <h4 class="hidden md:block text-xl text-gray-400">{{ bar.adresse }} - {{ bar.ville }} - {{ bar.pays }}</h4>
                        <h3 class="hidden md:block font-bold text-2xl text-gray-700">{{ bar.nom }}</h3>
                        <br>
                        <p class="text-gray-600 text-justify">{{ evenement.description }}</p>
                        <a class="flex items-baseline mt-3 text-blue-600 hover:text-blue-900 focus:text-blue-900" href="{{ path('evenement_participe', {id: evenement.id, participe: 1}) }}">
                            <span>Participer</span>
                            <span class="text-xs ml-1">&#x279c;</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    {% endfor %}



    {% for hotel in evenement.hotels %}
        <div class="mb-5">
            <a href="{{ path('hotel_show', {'urlName': hotel.urlName}) }}" class="block rounded-lg relative p-5 transform transition-all duration-300 scale-100 hover:scale-95" style="background: url({{ asset('/uploads/' ~ hotel.picture) }}) center; background-size: cover;">
                <div class="h-48"></div>
                <h2 class="text-blue-100 text-2xl font-bold leading-tight mb-3 pr-5">{{ hotel.nom }} XX {{ evenement.titre }}</h2>
                <div class="flex w-full items-center text-sm text-gray-300 font-medium">
                    <div class="flex-1 flex items-center">
                    </div>
                </div>
                <div class="text-blue-100">
                    {{ evenement.date ? evenement.date|date('d-m-Y') : '' }}
                </div>
            </a>
        </div>

    <div class="container mx-auto my-5">

        <div class="relative rounded-lg flex flex-col md:flex-row items-center md:shadow-xl md:h-72 mx-2">

            <div class="z-0 order-1 md:order-2 relative w-full md:w-2/5 h-80 md:h-full overflow-hidden rounded-lg md:rounded-none md:rounded-r-lg">
                <div class="absolute inset-0 w-full h-full object-fill object-center bg-blue-400 bg-opacity-30 bg-cover bg-bottom" style="background-image: url({{ asset('/uploads/' ~ evenement.picture) }}); background-blend-mode: multiply;"></div>
                <div class="md:hidden absolute inset-0 h-full p-6 pb-6 flex flex-col-reverse justify-start items-start bg-gradient-to-b from-transparent via-transparent to-gray-900">
                    <h3 class="w-full font-bold text-2xl text-white leading-tight mb-2"></h3>
                    <h4 class="w-full text-xl text-gray-100 leading-tight"></h4>
                </div>
                <svg class="hidden md:block absolute inset-y-0 h-full w-24 fill-current text-white -ml-12" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <polygon points="50,0 100,0 50,100 0,100" />
                </svg>
            </div>

            <div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 bg-white flex items-center -mt-6 md:mt-0">
                <div class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none">
                    <h4 class="hidden md:block text-xl text-gray-400">{{ hotel.adresse }} - {{ hotel.ville }} - {{ hotel.pays }}</h4>
                    <h3 class="hidden md:block font-bold  text-2xl text-gray-700">{{ hotel.nom }}</h3>
                    <br>
                    <p class="text-gray-600 text-justify">{{ evenement.description }}</p>
                    <a class="flex items-baseline mt-3 text-blue-600 hover:text-blue-900 focus:text-blue-900" href="{{ path('evenement_participe', {id: evenement.id, participe: 1}) }}">
                        <span>Participer</span>
                        <span class="text-xs ml-1">&#x279c;</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
<br>
<br>
<div class="lg:flex shadow border-gray-400 bg-white -mt-14 ">
    <div class="w-full  lg:w-11/12 xl:w-full px-1 bg-white py-5 lg:px-2 lg:py-2 tracking-wide dark:bg-gray-800">
        <div class="flex flex-row lg:justify-start justify-center">
            <div class="text-gray-700 font-medium text-sm text-center h-36 lg:text-left px-2 dark:text-white">
                PARTICIPANTS
                <ul>
                    <div @click="open = !open" class="relative border-transparent py-3" :class="{'border-indigo-700 transform transition duration-300 ': open}" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100">
                        <div class="flex justify-center items-center mt-4 mr-12 cursor-pointer">
                            <div class="flex">
                                {% for participe in evenement.userevents %}
                                {% if participe.response is same as 1 %}
                                <div class="w-12 h-12 rounded-full overflow-hidden border-2 dark:border-white border-gray-900">
                                    <img src="{{ asset("/uploads/" ~ participe.user.picture) }}" alt="" class="w-full h-full object-cover">
                                </div>
                            </div>
                            <div class="flex dark:text-white text-gray-900 text-lg">
                                {{ participe.user.prenom }}
                                <div class="cursor-pointer">

                                    {% else %}
                                    {% endif %}
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </div>
</div>

    {% if is_granted("ROLE_ADMIN") %}
    <a href="{{ path('evenement_index') }}">back to list</a>

    <a href="{{ path('evenement_edit', {'urlName': evenement.urlName}) }}">edit</a>

    {{ include('evenement/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}