src/Entity/Jet.php
<?php

namespace App\Entity;

use App\Repository\JetRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=JetRepository::class)
 * @Vich\Uploadable
 */
class Jet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $aeroportdestination;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $aeroportdepart;


    /**
     * @ORM\Column(type="time")
     */
    private $heureDepart;

    /**
     * @ORM\Column(type="time")
     */
    private $heureArrivee;

    /**
     * @ORM\ManyToMany(targetEntity=Evenement::class, inversedBy="jets")
     */
    private $evenement;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PaysDepart;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PaysDestination;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @Vich\UploadableField(mapping="poster_file", fileNameProperty="picture")
     * @var File | null
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/png", "image/webp", "image/jpg"},
     * )
     */
    private $posterFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $villeDepart;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $VilleDestination;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlName;



    public function __construct()
    {
        $this->evenement = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }


    public function getAeroportDestination(): ?string
    {
        return $this->aeroportdestination;
    }

    public function setAeroportDestination(string $aeroportdestination): self
    {
        $this->aeroportdestination = $aeroportdestination;

        return $this;
    }

    public function getAeroportDepart(): ?string
    {
        return $this->aeroportdepart;
    }

    public function setAeroportDepart(string $aeroportdepart): self
    {
        $this->aeroportdepart = $aeroportdepart;

        return $this;
    }

    public function getHeureDepart(): ?\DateTimeInterface
    {
        return $this->heureDepart;
    }

    public function setHeureDepart(\DateTimeInterface $heureDepart): self
    {
        $this->heureDepart = $heureDepart;

        return $this;
    }

    public function getHeureArrivee(): ?\DateTimeInterface
    {
        return $this->heureArrivee;
    }

    public function setHeureArrivee(\DateTimeInterface $heureArrivee): self
    {
        $this->heureArrivee = $heureArrivee;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenement(): Collection
    {
        return $this->evenement;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenement->contains($evenement)) {
            $this->evenement[] = $evenement;
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        $this->evenement->removeElement($evenement);

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPaysDepart(): ?string
    {
        return $this->PaysDepart;
    }

    public function setPaysDepart(string $PaysDepart): self
    {
        $this->PaysDepart = $PaysDepart;

        return $this;
    }

    public function getPaysDestination(): ?string
    {
        return $this->PaysDestination;
    }

    public function setPaysDestination(string $PaysDestination): self
    {
        $this->PaysDestination = $PaysDestination;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function setPosterFile(File $image = null): Jet
    {
        $this->posterFile = $image;
        return $this;
    }

    public function getPosterFile(): ?File
    {
        return $this->posterFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdateAt(File $image = null)
    {
        $this->updatedAt = $image;
        if ($image) {
            $this->updatedAt = new DateTime('now');
        }
    }

    public function getVilleDepart(): ?string
    {
        return $this->villeDepart;
    }

    public function setVilleDepart(string $villeDepart): self
    {
        $this->villeDepart = $villeDepart;

        return $this;
    }

    public function getVilleDestination(): ?string
    {
        return $this->VilleDestination;
    }

    public function setVilleDestination(string $VilleDestination): self
    {
        $this->VilleDestination = $VilleDestination;

        return $this;
    }

    public function getUrlName(): ?string
    {
        return $this->urlName;
    }

    public function setUrlName(string $urlName): self
    {
        $this->urlName = $urlName;

        return $this;
    }

}

src/Form/JetType.php
<?php

namespace App\Form;

use App\Entity\Jet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

class JetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('aeroportdepart')
            ->add('villeDepart')
            ->add('paysDepart')
            ->add('heureDepart')
            ->add('aeroportdestination', TextType::class)
            ->add('villeDestination')
            ->add('paysDestination')
            ->add('heureArrivee')
            ->add('date')
            ->add('posterFile', VichFileType::class, [
                'required'      => false,
                'allow_delete'  => true, // not mandatory, default is true
                'download_uri' => true, // not mandatory, default is true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Jet::class,
        ]);
    }
}

src/Controller/JetController.php
<?php

namespace App\Controller;

use App\Entity\Jet;
use App\Form\JetType;
use App\Repository\JetRepository;
use App\Service\UrlName;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/jet', name: 'jet_')]
class JetController extends AbstractController
{
    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(JetRepository $jetRepository): Response
    {
        return $this->render('jet/index.html.twig', [
            'jets' => $jetRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    /**
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, UrlName $urlName): Response
    {
        $jet = new Jet();
        $form = $this->createForm(JetType::class, $jet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            //Appel du service
            $urlName = $urlName->generate($jet->getNom());
            $jet->setUrlName($urlName);
            $entityManager->persist($jet);
            $entityManager->flush();

            return $this->redirectToRoute('jet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('jet/new.html.twig', [
            'jet' => $jet,
            'form' => $form,
        ]);
    }

    #[Route('/{urlName}', name: 'show', methods: ['GET'])]
    public function show(Jet $jet): Response
    {
        return $this->render('jet/show.html.twig', [
            'jet' => $jet,
        ]);
    }

    #[Route('/{urlName}/edit', name: 'edit', methods: ['GET', 'POST'])]
    /**
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Jet $jet): Response
    {
        $form = $this->createForm(JetType::class, $jet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('jet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('jet/edit.html.twig', [
            'jet' => $jet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    /**
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Jet $jet): Response
    {
        if ($this->isCsrfTokenValid('delete'.$jet->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($jet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('jet_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/jet/_delete_form.html.twig
<form method="post" action="{{ path('jet_delete', {'id': jet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ jet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/jet/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/jet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Jet{% endblock %}

{% block body %}
    <h1>Edit Jet</h1>

    {{ include('jet/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('jet_index') }}">back to list</a>

    {{ include('jet/_delete_form.html.twig') }}
{% endblock %}

templates/jet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jet{% endblock %}

{% block body %}

    <div class="bg-white">
    <h4 class="text-2xl text-center mt-8 font-bold">Séction Jets Privés (Ultra membres)</h4>
    {% if is_granted("ROLE_ADMIN") %}
    <a href="{{ path('jet_new') }}">Create new</a>
    {% endif %}
    <div class="flex justify-end mr-2">
        <a href="{{ path('home') }}">Retour</a>
    </div>
    {% for jet in jets %}
        {% if (loop.index %2) != 0 %}
        {% if is_granted("ROLE_ADMIN") %}
            <a href="{{ path('jet_edit', {'urlName': jet.urlName}) }}">Editer</a>
            {% endif %}
            <div class="flex -mx-1 mb-5">
            <div class="w-1/2 px-1">
                <a href="{{ path('jet_show', {'urlName': jet.urlName}) }}" class="block mb-2 p-5 rounded overflow-hidden transform transition-all duration-300 scale-100 hover:scale-95" style="background: url({{ asset('/uploads/' ~ jet.picture) }}) center; background-size: cover;">
                    <div class="h-48"></div>
                    <h3 class="text-lg font-bold text-blue-100 mt-12 leading-tight">{{ jet.nom }}</h3>
                    <h3 class="text-lg font-bold text-blue-100  leading-tight"> {{ jet.aeroportdepart }} - {{ jet.heuredepart|date('H:i')}} </h3>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ jet.aeroportdestination }} - {{ jet.heurearrivee|date('H:i')}} </h3>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight">{{ jet.date|date('D') }} - {{ jet.date|date('d/m/Y') }}</h3>
                </a>
            </div>
        {% else %}
            <div class="w-1/2 px-1">
                <a href="{{ path('jet_show', {'urlName': jet.urlName}) }}" class="block mb-2 p-5 rounded overflow-hidden transform transition-all duration-300 scale-100 hover:scale-95" style="background: url({{ asset('/uploads/' ~ jet.picture) }}) center; background-size: cover;">
                    <div class="h-48"></div>
                    <h3 class="text-lg font-bold text-blue-100 mt-12 leading-tight">{{ jet.nom }}</h3>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ jet.aeroportdepart }} - {{ jet.heuredepart|date('H:i')}} </h3>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight"> {{ jet.aeroportdestination }} - {{ jet.heurearrivee|date('H:i')}} </h3>
                    <h3 class="text-lg font-bold text-blue-100 leading-tight">{{ jet.date|date('D') }} - {{ jet.date|date('d/m/Y') }}</h3>

                </a>
            {% if is_granted("ROLE_ADMIN") %}
                <a href="{{ path('jet_edit', {'urlName': jet.urlName}) }}">Editer</a>
                {% endif %}
            </div>
            </div>
        {% endif %}
    {% else %}
        <tr>
            <td colspan="8">no records found</td>
        </tr>
        </div>
    {% endfor %}
{% endblock %}

templates/jet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Jet{% endblock %}

{% block body %}
    <h1>Create new Jet</h1>

    {{ include('jet/_form.html.twig') }}

    <a href="{{ path('jet_index') }}">back to list</a>
{% endblock %}

templates/jet/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jet{% endblock %}

{% block body %}

    <div class="container mx-auto my-5">
        <a href="{{ path('jet_index') }}">Revenir aux choix de jet</a>
        <div class="relative rounded-lg flex flex-col md:flex-row items-center md:shadow-xl md:h-72 mx-2">

            <div class="z-0 order-1 md:order-2 relative w-full md:w-2/5 h-80 md:h-full overflow-hidden rounded-lg md:rounded-none md:rounded-r-lg">
                <div class="absolute inset-0 w-full h-full object-fill object-center bg-blue-400 bg-opacity-30 bg-cover bg-bottom" style="background-image: url({{ asset('/uploads/' ~ jet.picture) }}); background-blend-mode: multiply;"></div>
                <div class="md:hidden absolute inset-0 h-full p-6 pb-6 flex flex-col-reverse justify-start items-start bg-gradient-to-b from-transparent via-transparent to-gray-900">
                    <h3 class="w-full font-bold text-2xl text-white leading-tight mb-2"></h3>
                    <h4 class="w-full text-xl text-gray-100 leading-tight"></h4>
                </div>
                <svg class="hidden md:block absolute inset-y-0 h-full w-24 fill-current text-white -ml-12" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <polygon points="50,0 100,0 50,100 0,100" />
                </svg>
            </div>

            <div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 bg-white flex items-center -mt-6 md:mt-0">
                <div class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none">
                    <h4 class="hidden md:block text-xl text-gray-400">{{ jet.aeroportDepart }} {{ jet.villeDepart}} {{ jet.paysDepart }} <br> To <br> {{ jet.aeroportDestination }} {{ jet.villeDestination}} {{ jet.paysDestination }}</h4>
                    <h3 class="hidden md:block font-bold mt-2 text-gray-700">{{ jet.date|date('d/m/Y') }}</h3>
                    <br>
                    <h4 class="hidden md:block text-xl text-gray-400"> Heure décollage : {{ jet.heureDepart|date('H:i') }} <br> Heure d'arrivée : {{ jet.heureArrivee|date('H:i') }}</h4>
                    <br>
                    {% for evenement in jet.evenement %}
                    <p class="text-gray-600 text-justify">Evenements à venir :</p>
                    <a class="flex items-baseline mt-3 text-blue-600 hover:text-blue-900 focus:text-blue-900" href="{{ path('evenement_show', {'urlName': evenement.urlName}) }}">
                        {{ evenement.titre }}
                        {% else %}
                        <div class="mb-4">
                            Pas d'évènements de prévu
                        </div>

                {% endfor %}

                </a>
            </div>
        </div>
    </div>
    </div>

    {% if is_granted("ROLE_ADMIN") %}
    <a href="{{ path('jet_index') }}">back to list</a>

    <a href="{{ path('jet_edit', {'urlName': jet.urlName}) }}">edit</a>

    {{ include('jet/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}